name: softi_firebase
description: A new Flutter package project.
version: 0.0.1
author:
homepage:
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  softi_common:
      path: ../package_flutter_common
  
  # softi_common:
  #   git:
  #     url: https://github.com/atoumbre/package_flutter_common.git
  #     ref: v0.3.1
  
  google_sign_in: ^5.0.1
  sign_in_with_apple: ^3.0.0

  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  firebase_dynamic_links: 2.0.0-dev.0
  cloud_firestore: ^1.0.3
  firebase_storage: ^8.0.1
  firebase_database: ^7.0.0-dev.0

  # flutter packages pub run build_runner watch --delete-conflicting-outputs
  # flutter packages pub run build_runner build --delete-conflicting-outputs
dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:

  
flutter:

